on:
  workflow_dispatch:
    inputs:
      envchoice:
        description: 'Runner'
        required: true
        default: ctdev 
        type: choice
        options:
        - ctdev
        - dev1
        - dev2
        - qa
        - prd
        
env:
  envchoice: ${{ inputs.envchoice }} 
  lchoice1: Hello

jobs:
  update-env:
    name: Check Test
    runs-on: ubuntu-latest
    steps:
    - id: step1
      if: env.envchoice == 'ctdev' &&  success()
      env:
          lchoice2: New2
      run: |
        echo "lchoice1=new" >> $GITHUB_ENV
        echo $lchoice1
        echo $lchoice2
    - id: step2
      run: |
        echo $lchoice1
        echo $lchoice2
        
  check-test2:
    name: Check Test2
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: |
        echo ${{ env.envchoice }}
        echo ${{ env.lchoice1 }} 
        echo ${{ env.lchoice2 }} 
      
