on:
  workflow_dispatch:
    inputs:
      envchoice:
        description: 'Runner'
        required: true
        default: 'warning' 
        type: choice
        options:
        - ctdev
        - dev1
        - dev2
        - qa
        - prd
        
env:
  envchoice: ${{ inputs.envchoice }} 

jobs:
  check-test:
    name: Check Test
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: echo "$envchoice"
      
